# https://docs.gradle.org/current/userguide/github-actions.html
name: build

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout project sources
                uses: actions/checkout@v4

            -   name: Setup OpenJDK 17
                uses: actions/setup-java@v4
                with:
                    distribution: 'adopt'
                    java-version: '17.0.6'

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3

            -   name: Execute Gradle build
                run: ./gradlew build
